FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY App.js /usr/share/nginx/html/App.js
COPY Style.css /usr/share/nginx/html/Style.css
COPY nginx.conf /etc/nginx/conf.d/default.conf
